Task/Project initialization, authentication and authorization implementation
DaryaZel/Cinema-Ticket-Reservation-System__Backend pull request #1
Opened 2021-12-29 09:38 UTC by DaryaZel

Project initialization with setting up a REST API using Express. Data storage is implemented with MongoDB. Authentication and authorization are implemented with the support of JSON web tokens and roles identification.

2022-01-18 12:19 UTC, butterflyInACast requested changes

2022-01-18 12:19 UTC, butterflyInACast commented on Movies/moviesModel.js
> +    liveStory: { type: String, required: true }
I believe you will ad it later, but is obviously that the movie shoud have more fields that this. Like its duration, language, age restriction, etc. 
Also it is better to rename the 'movieName' to just 'name', because you will always get it from the object like movie.name,  so it will be always clear that this is a movie name.  But it is for your choice

2022-01-18 12:19 UTC, butterflyInACast commented on Movies/moviesRouter.js
> +router.delete('/:id', Controller.delete);
Whebn you have different methods for the same route, it is vetter to use router.route('/path').get(...).post(...).put(...).delete(...)

2022-01-18 12:19 UTC, butterflyInACast commented on index.js
> +const PORT = 5000;
Move it to the config file

2022-01-26 14:11 UTC, DaryaZel commented on Authorization/User.js
> +    roles: [{ type: String, ref: 'Role' }]
fixed

2022-02-02 10:34 UTC, merged